In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.cm as cm
from warnings import filterwarnings
filterwarnings ('ignore')

In [4]:
file_path = '/content/drive/MyDrive/Data Project/Covid/BehaviourDataset.csv'

In [5]:
df = pd.read_csv(file_path,encoding='UTF-16',sep='\t')
df.head(3)

,impact_on_academic_life,impact_on_mental_health,impact_on_social_life,Label
0,আমাদের শিক্ষাব্যবস্থা অনলাইন হওয়ার ক্ষেত্রে প...,লকডাউন এর কারণে দিন দিন ডিপ্রেশনের কারণ বেড়েই...,করোনার কারণে সামাজিক দূরত্ব অনেক বেড়ে যায়,Negative
1,অনলাইন শিক্ষাব্যবস্থা আমার কাছে খুবই চাপ যুক্ত...,অনলাইন শিক্ষা ব্যবস্থার ক্ষেত্রে আমি খুবই মানস...,অনলাইন শিক্ষা ব্যবস্থার ক্ষেত্রে আমি খুবই মানস...,Negative
2,অনলাইন থেকে আমার কাজের দক্ষতা বৃদ্ধির জন্য আমি...,পরিবারের সবার সাথে অনেক সময় কাটানো হয়েছে তাই...,পরিবার আত্মীয়-স্বজন এবং বন্ধু-বান্ধবের সাথে আ...,Positive

In [6]:
# =====================================================================
# BanglaBERT Fine-Tuning vs. Original Thesis Baselines
# Run this in Google Colab with GPU enabled:
# Runtime -> Change runtime type -> T4 GPU
# =====================================================================

# ---------------------------------------------------------------------
# STEP 0 — Install required libraries (Colab doesn't have these by default)
# ---------------------------------------------------------------------
!pip install -q transformers datasets scikit-learn accelerate

# ---------------------------------------------------------------------
# STEP 1 — Load the dataset
# ---------------------------------------------------------------------

df.columns = [c.strip() for c in df.columns]  # remove stray leading space in column names

print(f"Loaded {len(df)} rows")
print(df["Label"].value_counts())

# Convert Positive/Negative to 1/0, same as the original paper's label encoding
df["label_encoded"] = df["Label"].map({"Positive": 0, "Negative": 1})

TEXT_COLUMNS = {
    "academic": "impact_on_academic_life",
    "mental": "impact_on_mental_health",
    "social": "impact_on_social_life",
}

# Baselines from the original thesis (Tables 5 and 6), for the final comparison
ORIGINAL_BASELINES = {
    "academic": {"best_ml": ("SGD", 95.00), "best_dl": ("BiLSTM", 92.50)},
    "mental":   {"best_ml": ("KNN", 93.75), "best_dl": ("LSTM", 98.75)},
    "social":   {"best_ml": ("SGD/Multi-NB", 95.00), "best_dl": ("BiLSTM/CNN/CNN-LSTM", 92.50)},
}

# ---------------------------------------------------------------------
# STEP 2 — Imports for fine-tuning
# ---------------------------------------------------------------------
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from datasets import Dataset

MODEL_NAME = "sagorsarker/bangla-bert-base"
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds),
        "precision": precision_score(labels, preds),
        "recall": recall_score(labels, preds),
    }


def fine_tune_on_column(column_key, text_column):
    print(f"\n{'='*60}\nFine-tuning on: {column_key} ({text_column})\n{'='*60}")

    texts = df[text_column].astype(str).tolist()
    labels = df["label_encoded"].tolist()

    # Same 80/20 split logic as the original paper, stratified to keep
    # the class balance even in the smaller test set
    train_texts, test_texts, train_labels, test_labels = train_test_split(
        texts, labels, test_size=0.2, stratify=labels, random_state=42
    )

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    def tokenize(batch):
        return tokenizer(batch["text"], padding="max_length", truncation=True, max_length=64)

    train_ds = Dataset.from_dict({"text": train_texts, "label": train_labels}).map(tokenize, batched=True)
    test_ds = Dataset.from_dict({"text": test_texts, "label": test_labels}).map(tokenize, batched=True)

    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2).to(device)

    args = TrainingArguments(
        output_dir=f"./results_{column_key}",
        num_train_epochs=4,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=5,
        learning_rate=2e-5,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=test_ds,
        compute_metrics=compute_metrics,
    )

    trainer.train()
    results = trainer.evaluate()
    return results


# ---------------------------------------------------------------------
# STEP 3 — Run fine-tuning for all three columns and collect results
# ---------------------------------------------------------------------
all_results = {}
for key, col in TEXT_COLUMNS.items():
    all_results[key] = fine_tune_on_column(key, col)

# ---------------------------------------------------------------------
# STEP 4 — Final comparison table: BanglaBERT vs. original thesis results
# ---------------------------------------------------------------------
print("\n\n" + "=" * 70)
print("FINAL COMPARISON: BanglaBERT vs. Original Thesis Results")
print("=" * 70)

comparison_rows = []
for key in TEXT_COLUMNS:
    bert_acc = all_results[key]["eval_accuracy"] * 100
    bert_f1 = all_results[key]["eval_f1"] * 100
    best_ml_name, best_ml_acc = ORIGINAL_BASELINES[key]["best_ml"]
    best_dl_name, best_dl_acc = ORIGINAL_BASELINES[key]["best_dl"]

    comparison_rows.append({
        "Column": key,
        "BanglaBERT Accuracy (%)": round(bert_acc, 2),
        "BanglaBERT F1 (%)": round(bert_f1, 2),
        f"Best ML ({best_ml_name})": best_ml_acc,
        f"Best DL ({best_dl_name})": best_dl_acc,
        "BanglaBERT beats both?": "Yes" if bert_acc > max(best_ml_acc, best_dl_acc) else "No",
    })

comparison_df = pd.DataFrame(comparison_rows)
print(comparison_df.to_string(index=False))

comparison_df.to_csv("/content/drive/MyDrive/Data Project/Covid/banglabert_vs_thesis_comparison.csv", index=False)
print("\nSaved comparison table to banglabert_vs_thesis_comparison.csv")

Loaded 400 rows
Label
Negative    200
Positive    200
Name: count, dtype: int64
Using device: cuda

============================================================
Fine-tuning on: academic (impact_on_academic_life)
============================================================

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/491 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/2.24M [00:00<?, ?B/s]

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  660MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

============================================================
Fine-tuning on: mental (impact_on_mental_health)
============================================================

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

============================================================
Fine-tuning on: social (impact_on_social_life)
============================================================

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

======================================================================
FINAL COMPARISON: BanglaBERT vs. Original Thesis Results
======================================================================
  Column  BanglaBERT Accuracy (%)  BanglaBERT F1 (%)  Best ML (SGD)  Best DL (BiLSTM) BanglaBERT beats both?  Best ML (KNN)  Best DL (LSTM)  Best ML (SGD/Multi-NB)  Best DL (BiLSTM/CNN/CNN-LSTM)
academic                    87.50              86.11           95.0              92.5                     No            NaN             NaN                     NaN                            NaN
  mental                    92.50              92.68            NaN               NaN                     No          93.75           98.75                     NaN                            NaN
  social                    93.75              93.83            NaN               NaN                     No            NaN             NaN                    95.0                           92.5

Saved comparison table to banglabert_vs_thesis_comparison.csv

In [ ]:
# =====================================================================
# BanglaBERT Fine-Tuning vs. Original Thesis Baselines — 5-Fold CV
# Run this in Google Colab with GPU enabled:
# Runtime -> Change runtime type -> T4 GPU
#
# Difference from the single-split version: each column is evaluated
# with 5-fold cross-validation instead of one 80/20 split, so the
# result is a mean +/- standard deviation rather than a single number
# that could swing on just a handful of examples (the test set is
# only 80 rows, so a single split is fragile).
# =====================================================================

!pip install -q transformers datasets scikit-learn accelerate

import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from datasets import Dataset

# ---------------------------------------------------------------------
# STEP 1 — Load the dataset
# ---------------------------------------------------------------------

df.columns = [c.strip() for c in df.columns]
df["label_encoded"] = df["Label"].map({"Positive": 0, "Negative": 1})

TEXT_COLUMNS = {
    "academic": "impact_on_academic_life",
    "mental": "impact_on_mental_health",
    "social": "impact_on_social_life",
}

ORIGINAL_BASELINES = {
    "academic": {"best_ml": ("SGD", 95.00), "best_dl": ("BiLSTM", 92.50)},
    "mental":   {"best_ml": ("KNN", 93.75), "best_dl": ("LSTM", 98.75)},
    "social":   {"best_ml": ("SGD/Multi-NB", 95.00), "best_dl": ("BiLSTM/CNN/CNN-LSTM", 92.50)},
}

MODEL_NAME = "sagorsarker/bangla-bert-base"
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

N_FOLDS = 5


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds),
        "precision": precision_score(labels, preds),
        "recall": recall_score(labels, preds),
    }


def tokenize_batch(tokenizer, texts):
    return tokenizer(texts, padding="max_length", truncation=True, max_length=64)


def cross_validate_column(column_key, text_column):
    print(f"\n{'='*60}\n5-Fold CV on: {column_key} ({text_column})\n{'='*60}")

    texts = df[text_column].astype(str).tolist()
    labels = df["label_encoded"].to_numpy()
    texts = np.array(texts)

    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=42)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    fold_results = []

    for fold_idx, (train_idx, val_idx) in enumerate(skf.split(texts, labels), start=1):
        print(f"\n--- Fold {fold_idx}/{N_FOLDS} ---")

        train_texts, val_texts = texts[train_idx].tolist(), texts[val_idx].tolist()
        train_labels, val_labels = labels[train_idx].tolist(), labels[val_idx].tolist()

        train_ds = Dataset.from_dict({"text": train_texts, "label": train_labels}).map(
            lambda b: tokenize_batch(tokenizer, b["text"]), batched=True
        )
        val_ds = Dataset.from_dict({"text": val_texts, "label": val_labels}).map(
            lambda b: tokenize_batch(tokenizer, b["text"]), batched=True
        )

        # Fresh model each fold — reusing a trained model across folds
        # would leak information between folds
        model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2).to(device)

        args = TrainingArguments(
            output_dir=f"./results_{column_key}_fold{fold_idx}",
            num_train_epochs=4,
            per_device_train_batch_size=16,
            per_device_eval_batch_size=16,
            eval_strategy="epoch",
            save_strategy="no",
            logging_steps=50,
            learning_rate=2e-5,
            report_to="none",
            disable_tqdm=True,
        )

        trainer = Trainer(
            model=model,
            args=args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics,
        )

        trainer.train()
        fold_metrics = trainer.evaluate()
        fold_results.append(fold_metrics)

        print(f"Fold {fold_idx} accuracy: {fold_metrics['eval_accuracy']*100:.2f}%")

        # free GPU memory before the next fold
        del model, trainer
        torch.cuda.empty_cache()

    accs = [r["eval_accuracy"] * 100 for r in fold_results]
    f1s = [r["eval_f1"] * 100 for r in fold_results]

    return {
        "mean_accuracy": np.mean(accs),
        "std_accuracy": np.std(accs),
        "mean_f1": np.mean(f1s),
        "std_f1": np.std(f1s),
        "fold_accuracies": accs,
    }


# ---------------------------------------------------------------------
# STEP 2 — Run 5-fold CV for all three columns
# ---------------------------------------------------------------------
all_results = {}
for key, col in TEXT_COLUMNS.items():
    all_results[key] = cross_validate_column(key, col)

# ---------------------------------------------------------------------
# STEP 3 — Final comparison table
# ---------------------------------------------------------------------
print("\n\n" + "=" * 70)
print("FINAL COMPARISON: BanglaBERT (5-fold CV) vs. Original Thesis Results")
print("=" * 70)

comparison_rows = []
for key in TEXT_COLUMNS:
    r = all_results[key]
    best_ml_name, best_ml_acc = ORIGINAL_BASELINES[key]["best_ml"]
    best_dl_name, best_dl_acc = ORIGINAL_BASELINES[key]["best_dl"]

    comparison_rows.append({
        "Column": key,
        "BanglaBERT Acc (mean ± std, %)": f"{r['mean_accuracy']:.2f} ± {r['std_accuracy']:.2f}",
        "BanglaBERT F1 (mean, %)": round(r["mean_f1"], 2),
        f"Best ML ({best_ml_name})": best_ml_acc,
        f"Best DL ({best_dl_name})": best_dl_acc,
        "Fold accuracies": [round(a, 1) for a in r["fold_accuracies"]],
    })

comparison_df = pd.DataFrame(comparison_rows)
pd.set_option("display.width", 150)
print(comparison_df.to_string(index=False))

comparison_df.to_csv("banglabert_cv_vs_thesis_comparison.csv", index=False)
print("\nSaved to banglabert_cv_vs_thesis_comparison.csv")

Using device: cuda

============================================================
5-Fold CV on: academic (impact_on_academic_life)
============================================================

--- Fold 1/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3144', 'eval_accuracy': '0.8375', 'eval_f1': '0.8312', 'eval_precision': '0.8649', 'eval_recall': '0.8', 'eval_runtime': '0.3153', 'eval_samples_per_second': '253.7', 'eval_steps_per_second': '15.86', 'epoch': '1'}
{'eval_loss': '0.2933', 'eval_accuracy': '0.8875', 'eval_f1': '0.8941', 'eval_precision': '0.8444', 'eval_recall': '0.95', 'eval_runtime': '0.3179', 'eval_samples_per_second': '251.7', 'eval_steps_per_second': '15.73', 'epoch': '2'}
{'loss': '0.3', 'grad_norm': '0.6453', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2726', 'eval_accuracy': '0.9', 'eval_f1': '0.9048', 'eval_precision': '0.8636', 'eval_recall': '0.95', 'eval_runtime': '0.3265', 'eval_samples_per_second': '245', 'eval_steps_per_second': '15.31', 'epoch': '3'}
{'eval_loss': '0.3249', 'eval_accuracy': '0.8875', 'eval_f1': '0.8941', 'eval_precision': '0.8444', 'eval_recall': '0.95', 'eval_runtime': '0.3267', 'eval_samples_per_second': '244.9', 'eval_steps_per_second': '15.3', 'epoch': '4'}
{'train_runtime': '16.36', 'train_samples_per_second': '78.24', 'train_steps_per_second': '4.89', 'train_loss': '0.2188', 'epoch': '4'}
{'eval_loss': '0.3249', 'eval_accuracy': '0.8875', 'eval_f1': '0.8941', 'eval_precision': '0.8444', 'eval_recall': '0.95', 'eval_runtime': '0.308', 'eval_samples_per_second': '259.8', 'eval_steps_per_second': '16.23', 'epoch': '4'}
Fold 1 accuracy: 88.75%

--- Fold 2/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.2971', 'eval_accuracy': '0.8875', 'eval_f1': '0.8941', 'eval_precision': '0.8444', 'eval_recall': '0.95', 'eval_runtime': '0.3316', 'eval_samples_per_second': '241.3', 'eval_steps_per_second': '15.08', 'epoch': '1'}
{'eval_loss': '0.2027', 'eval_accuracy': '0.95', 'eval_f1': '0.9487', 'eval_precision': '0.9737', 'eval_recall': '0.925', 'eval_runtime': '0.3362', 'eval_samples_per_second': '237.9', 'eval_steps_per_second': '14.87', 'epoch': '2'}
{'loss': '0.3084', 'grad_norm': '5.858', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2052', 'eval_accuracy': '0.9375', 'eval_f1': '0.9367', 'eval_precision': '0.9487', 'eval_recall': '0.925', 'eval_runtime': '0.3418', 'eval_samples_per_second': '234', 'eval_steps_per_second': '14.63', 'epoch': '3'}
{'eval_loss': '0.2072', 'eval_accuracy': '0.9375', 'eval_f1': '0.9383', 'eval_precision': '0.9268', 'eval_recall': '0.95', 'eval_runtime': '0.3399', 'eval_samples_per_second': '235.4', 'eval_steps_per_second': '14.71', 'epoch': '4'}
{'train_runtime': '17.19', 'train_samples_per_second': '74.46', 'train_steps_per_second': '4.654', 'train_loss': '0.214', 'epoch': '4'}
{'eval_loss': '0.2072', 'eval_accuracy': '0.9375', 'eval_f1': '0.9383', 'eval_precision': '0.9268', 'eval_recall': '0.95', 'eval_runtime': '0.3191', 'eval_samples_per_second': '250.7', 'eval_steps_per_second': '15.67', 'epoch': '4'}
Fold 2 accuracy: 93.75%

--- Fold 3/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.2855', 'eval_accuracy': '0.9', 'eval_f1': '0.9024', 'eval_precision': '0.881', 'eval_recall': '0.925', 'eval_runtime': '0.344', 'eval_samples_per_second': '232.6', 'eval_steps_per_second': '14.54', 'epoch': '1'}
{'eval_loss': '0.1667', 'eval_accuracy': '0.95', 'eval_f1': '0.9487', 'eval_precision': '0.9737', 'eval_recall': '0.925', 'eval_runtime': '0.3519', 'eval_samples_per_second': '227.3', 'eval_steps_per_second': '14.21', 'epoch': '2'}
{'loss': '0.2919', 'grad_norm': '2.354', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.1692', 'eval_accuracy': '0.925', 'eval_f1': '0.9268', 'eval_precision': '0.9048', 'eval_recall': '0.95', 'eval_runtime': '0.3577', 'eval_samples_per_second': '223.7', 'eval_steps_per_second': '13.98', 'epoch': '3'}
{'eval_loss': '0.1644', 'eval_accuracy': '0.925', 'eval_f1': '0.9268', 'eval_precision': '0.9048', 'eval_recall': '0.95', 'eval_runtime': '0.3662', 'eval_samples_per_second': '218.5', 'eval_steps_per_second': '13.65', 'epoch': '4'}
{'train_runtime': '17.92', 'train_samples_per_second': '71.44', 'train_steps_per_second': '4.465', 'train_loss': '0.2019', 'epoch': '4'}
{'eval_loss': '0.1644', 'eval_accuracy': '0.925', 'eval_f1': '0.9268', 'eval_precision': '0.9048', 'eval_recall': '0.95', 'eval_runtime': '0.3493', 'eval_samples_per_second': '229', 'eval_steps_per_second': '14.31', 'epoch': '4'}
Fold 3 accuracy: 92.50%

--- Fold 4/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3571', 'eval_accuracy': '0.85', 'eval_f1': '0.8286', 'eval_precision': '0.9667', 'eval_recall': '0.725', 'eval_runtime': '0.3737', 'eval_samples_per_second': '214.1', 'eval_steps_per_second': '13.38', 'epoch': '1'}
{'eval_loss': '0.2366', 'eval_accuracy': '0.925', 'eval_f1': '0.9211', 'eval_precision': '0.9722', 'eval_recall': '0.875', 'eval_runtime': '0.3763', 'eval_samples_per_second': '212.6', 'eval_steps_per_second': '13.29', 'epoch': '2'}
{'loss': '0.2942', 'grad_norm': '3.258', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2349', 'eval_accuracy': '0.9125', 'eval_f1': '0.9091', 'eval_precision': '0.9459', 'eval_recall': '0.875', 'eval_runtime': '0.3859', 'eval_samples_per_second': '207.3', 'eval_steps_per_second': '12.96', 'epoch': '3'}
{'eval_loss': '0.2307', 'eval_accuracy': '0.9125', 'eval_f1': '0.9114', 'eval_precision': '0.9231', 'eval_recall': '0.9', 'eval_runtime': '0.3853', 'eval_samples_per_second': '207.6', 'eval_steps_per_second': '12.98', 'epoch': '4'}
{'train_runtime': '18.88', 'train_samples_per_second': '67.8', 'train_steps_per_second': '4.238', 'train_loss': '0.2011', 'epoch': '4'}
{'eval_loss': '0.2307', 'eval_accuracy': '0.9125', 'eval_f1': '0.9114', 'eval_precision': '0.9231', 'eval_recall': '0.9', 'eval_runtime': '0.3701', 'eval_samples_per_second': '216.2', 'eval_steps_per_second': '13.51', 'epoch': '4'}
Fold 4 accuracy: 91.25%

--- Fold 5/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3237', 'eval_accuracy': '0.8625', 'eval_f1': '0.8533', 'eval_precision': '0.9143', 'eval_recall': '0.8', 'eval_runtime': '0.3863', 'eval_samples_per_second': '207.1', 'eval_steps_per_second': '12.94', 'epoch': '1'}
{'eval_loss': '0.2448', 'eval_accuracy': '0.9125', 'eval_f1': '0.9091', 'eval_precision': '0.9459', 'eval_recall': '0.875', 'eval_runtime': '0.3759', 'eval_samples_per_second': '212.8', 'eval_steps_per_second': '13.3', 'epoch': '2'}
{'loss': '0.2945', 'grad_norm': '12.43', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.1922', 'eval_accuracy': '0.925', 'eval_f1': '0.925', 'eval_precision': '0.925', 'eval_recall': '0.925', 'eval_runtime': '0.3665', 'eval_samples_per_second': '218.3', 'eval_steps_per_second': '13.64', 'epoch': '3'}
{'eval_loss': '0.1839', 'eval_accuracy': '0.925', 'eval_f1': '0.925', 'eval_precision': '0.925', 'eval_recall': '0.925', 'eval_runtime': '0.3623', 'eval_samples_per_second': '220.8', 'eval_steps_per_second': '13.8', 'epoch': '4'}
{'train_runtime': '18.91', 'train_samples_per_second': '67.7', 'train_steps_per_second': '4.231', 'train_loss': '0.2144', 'epoch': '4'}
{'eval_loss': '0.1839', 'eval_accuracy': '0.925', 'eval_f1': '0.925', 'eval_precision': '0.925', 'eval_recall': '0.925', 'eval_runtime': '0.3421', 'eval_samples_per_second': '233.8', 'eval_steps_per_second': '14.62', 'epoch': '4'}
Fold 5 accuracy: 92.50%

============================================================
5-Fold CV on: mental (impact_on_mental_health)
============================================================

--- Fold 1/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3994', 'eval_accuracy': '0.875', 'eval_f1': '0.878', 'eval_precision': '0.8571', 'eval_recall': '0.9', 'eval_runtime': '0.3541', 'eval_samples_per_second': '226', 'eval_steps_per_second': '14.12', 'epoch': '1'}
{'eval_loss': '0.2512', 'eval_accuracy': '0.9125', 'eval_f1': '0.9157', 'eval_precision': '0.8837', 'eval_recall': '0.95', 'eval_runtime': '0.353', 'eval_samples_per_second': '226.6', 'eval_steps_per_second': '14.17', 'epoch': '2'}
{'loss': '0.4033', 'grad_norm': '6.127', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2711', 'eval_accuracy': '0.9125', 'eval_f1': '0.9176', 'eval_precision': '0.8667', 'eval_recall': '0.975', 'eval_runtime': '0.3533', 'eval_samples_per_second': '226.4', 'eval_steps_per_second': '14.15', 'epoch': '3'}
{'eval_loss': '0.2194', 'eval_accuracy': '0.925', 'eval_f1': '0.9286', 'eval_precision': '0.8864', 'eval_recall': '0.975', 'eval_runtime': '0.3557', 'eval_samples_per_second': '224.9', 'eval_steps_per_second': '14.06', 'epoch': '4'}
{'train_runtime': '18.01', 'train_samples_per_second': '71.08', 'train_steps_per_second': '4.442', 'train_loss': '0.2963', 'epoch': '4'}
{'eval_loss': '0.2194', 'eval_accuracy': '0.925', 'eval_f1': '0.9286', 'eval_precision': '0.8864', 'eval_recall': '0.975', 'eval_runtime': '0.3424', 'eval_samples_per_second': '233.6', 'eval_steps_per_second': '14.6', 'epoch': '4'}
Fold 1 accuracy: 92.50%

--- Fold 2/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3669', 'eval_accuracy': '0.85', 'eval_f1': '0.8537', 'eval_precision': '0.8333', 'eval_recall': '0.875', 'eval_runtime': '0.3525', 'eval_samples_per_second': '227', 'eval_steps_per_second': '14.19', 'epoch': '1'}
{'eval_loss': '0.2777', 'eval_accuracy': '0.9125', 'eval_f1': '0.9091', 'eval_precision': '0.9459', 'eval_recall': '0.875', 'eval_runtime': '0.3539', 'eval_samples_per_second': '226', 'eval_steps_per_second': '14.13', 'epoch': '2'}
{'loss': '0.343', 'grad_norm': '3.314', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2502', 'eval_accuracy': '0.8875', 'eval_f1': '0.8861', 'eval_precision': '0.8974', 'eval_recall': '0.875', 'eval_runtime': '0.3618', 'eval_samples_per_second': '221.1', 'eval_steps_per_second': '13.82', 'epoch': '3'}
{'eval_loss': '0.2519', 'eval_accuracy': '0.9125', 'eval_f1': '0.9114', 'eval_precision': '0.9231', 'eval_recall': '0.9', 'eval_runtime': '0.358', 'eval_samples_per_second': '223.5', 'eval_steps_per_second': '13.97', 'epoch': '4'}
{'train_runtime': '17.97', 'train_samples_per_second': '71.21', 'train_steps_per_second': '4.451', 'train_loss': '0.2515', 'epoch': '4'}
{'eval_loss': '0.2519', 'eval_accuracy': '0.9125', 'eval_f1': '0.9114', 'eval_precision': '0.9231', 'eval_recall': '0.9', 'eval_runtime': '0.3396', 'eval_samples_per_second': '235.6', 'eval_steps_per_second': '14.72', 'epoch': '4'}
Fold 2 accuracy: 91.25%

--- Fold 3/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.371', 'eval_accuracy': '0.875', 'eval_f1': '0.881', 'eval_precision': '0.8409', 'eval_recall': '0.925', 'eval_runtime': '0.3756', 'eval_samples_per_second': '213', 'eval_steps_per_second': '13.31', 'epoch': '1'}
{'eval_loss': '0.2997', 'eval_accuracy': '0.9', 'eval_f1': '0.8974', 'eval_precision': '0.9211', 'eval_recall': '0.875', 'eval_runtime': '0.3681', 'eval_samples_per_second': '217.3', 'eval_steps_per_second': '13.58', 'epoch': '2'}
{'loss': '0.3622', 'grad_norm': '6.838', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2985', 'eval_accuracy': '0.875', 'eval_f1': '0.881', 'eval_precision': '0.8409', 'eval_recall': '0.925', 'eval_runtime': '0.3784', 'eval_samples_per_second': '211.4', 'eval_steps_per_second': '13.21', 'epoch': '3'}
{'eval_loss': '0.2705', 'eval_accuracy': '0.9125', 'eval_f1': '0.9136', 'eval_precision': '0.9024', 'eval_recall': '0.925', 'eval_runtime': '0.3751', 'eval_samples_per_second': '213.3', 'eval_steps_per_second': '13.33', 'epoch': '4'}
{'train_runtime': '18.66', 'train_samples_per_second': '68.59', 'train_steps_per_second': '4.287', 'train_loss': '0.2623', 'epoch': '4'}
{'eval_loss': '0.2705', 'eval_accuracy': '0.9125', 'eval_f1': '0.9136', 'eval_precision': '0.9024', 'eval_recall': '0.925', 'eval_runtime': '0.3621', 'eval_samples_per_second': '221', 'eval_steps_per_second': '13.81', 'epoch': '4'}
Fold 3 accuracy: 91.25%

--- Fold 4/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.4584', 'eval_accuracy': '0.75', 'eval_f1': '0.697', 'eval_precision': '0.8846', 'eval_recall': '0.575', 'eval_runtime': '0.3655', 'eval_samples_per_second': '218.9', 'eval_steps_per_second': '13.68', 'epoch': '1'}
{'eval_loss': '0.3748', 'eval_accuracy': '0.8375', 'eval_f1': '0.8219', 'eval_precision': '0.9091', 'eval_recall': '0.75', 'eval_runtime': '0.3655', 'eval_samples_per_second': '218.9', 'eval_steps_per_second': '13.68', 'epoch': '2'}
{'loss': '0.3213', 'grad_norm': '2.021', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2944', 'eval_accuracy': '0.9', 'eval_f1': '0.9', 'eval_precision': '0.9', 'eval_recall': '0.9', 'eval_runtime': '0.3638', 'eval_samples_per_second': '219.9', 'eval_steps_per_second': '13.75', 'epoch': '3'}
{'eval_loss': '0.3012', 'eval_accuracy': '0.9', 'eval_f1': '0.8974', 'eval_precision': '0.9211', 'eval_recall': '0.875', 'eval_runtime': '0.3585', 'eval_samples_per_second': '223.2', 'eval_steps_per_second': '13.95', 'epoch': '4'}
{'train_runtime': '18.36', 'train_samples_per_second': '69.72', 'train_steps_per_second': '4.357', 'train_loss': '0.2375', 'epoch': '4'}
{'eval_loss': '0.3012', 'eval_accuracy': '0.9', 'eval_f1': '0.8974', 'eval_precision': '0.9211', 'eval_recall': '0.875', 'eval_runtime': '0.342', 'eval_samples_per_second': '233.9', 'eval_steps_per_second': '14.62', 'epoch': '4'}
Fold 4 accuracy: 90.00%

--- Fold 5/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3418', 'eval_accuracy': '0.85', 'eval_f1': '0.8537', 'eval_precision': '0.8333', 'eval_recall': '0.875', 'eval_runtime': '0.3565', 'eval_samples_per_second': '224.4', 'eval_steps_per_second': '14.02', 'epoch': '1'}
{'eval_loss': '0.3231', 'eval_accuracy': '0.875', 'eval_f1': '0.881', 'eval_precision': '0.8409', 'eval_recall': '0.925', 'eval_runtime': '0.3583', 'eval_samples_per_second': '223.3', 'eval_steps_per_second': '13.96', 'epoch': '2'}
{'loss': '0.3257', 'grad_norm': '1.971', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.3148', 'eval_accuracy': '0.8875', 'eval_f1': '0.8941', 'eval_precision': '0.8444', 'eval_recall': '0.95', 'eval_runtime': '0.3587', 'eval_samples_per_second': '223', 'eval_steps_per_second': '13.94', 'epoch': '3'}
{'eval_loss': '0.3339', 'eval_accuracy': '0.8875', 'eval_f1': '0.8941', 'eval_precision': '0.8444', 'eval_recall': '0.95', 'eval_runtime': '0.363', 'eval_samples_per_second': '220.4', 'eval_steps_per_second': '13.78', 'epoch': '4'}
{'train_runtime': '18.22', 'train_samples_per_second': '70.25', 'train_steps_per_second': '4.391', 'train_loss': '0.2266', 'epoch': '4'}
{'eval_loss': '0.3339', 'eval_accuracy': '0.8875', 'eval_f1': '0.8941', 'eval_precision': '0.8444', 'eval_recall': '0.95', 'eval_runtime': '0.3441', 'eval_samples_per_second': '232.5', 'eval_steps_per_second': '14.53', 'epoch': '4'}
Fold 5 accuracy: 88.75%

============================================================
5-Fold CV on: social (impact_on_social_life)
============================================================

--- Fold 1/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3389', 'eval_accuracy': '0.9', 'eval_f1': '0.9024', 'eval_precision': '0.881', 'eval_recall': '0.925', 'eval_runtime': '0.3574', 'eval_samples_per_second': '223.8', 'eval_steps_per_second': '13.99', 'epoch': '1'}
{'eval_loss': '0.2479', 'eval_accuracy': '0.9', 'eval_f1': '0.907', 'eval_precision': '0.8478', 'eval_recall': '0.975', 'eval_runtime': '0.359', 'eval_samples_per_second': '222.8', 'eval_steps_per_second': '13.93', 'epoch': '2'}
{'loss': '0.3345', 'grad_norm': '6.882', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2231', 'eval_accuracy': '0.9375', 'eval_f1': '0.9398', 'eval_precision': '0.907', 'eval_recall': '0.975', 'eval_runtime': '0.3696', 'eval_samples_per_second': '216.4', 'eval_steps_per_second': '13.53', 'epoch': '3'}
{'eval_loss': '0.2182', 'eval_accuracy': '0.925', 'eval_f1': '0.9268', 'eval_precision': '0.9048', 'eval_recall': '0.95', 'eval_runtime': '0.3708', 'eval_samples_per_second': '215.8', 'eval_steps_per_second': '13.48', 'epoch': '4'}
{'train_runtime': '18.35', 'train_samples_per_second': '69.75', 'train_steps_per_second': '4.359', 'train_loss': '0.2428', 'epoch': '4'}
{'eval_loss': '0.2182', 'eval_accuracy': '0.925', 'eval_f1': '0.9268', 'eval_precision': '0.9048', 'eval_recall': '0.95', 'eval_runtime': '0.3471', 'eval_samples_per_second': '230.5', 'eval_steps_per_second': '14.41', 'epoch': '4'}
Fold 1 accuracy: 92.50%

--- Fold 2/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3076', 'eval_accuracy': '0.875', 'eval_f1': '0.8684', 'eval_precision': '0.9167', 'eval_recall': '0.825', 'eval_runtime': '0.3648', 'eval_samples_per_second': '219.3', 'eval_steps_per_second': '13.71', 'epoch': '1'}
{'eval_loss': '0.2921', 'eval_accuracy': '0.85', 'eval_f1': '0.8286', 'eval_precision': '0.9667', 'eval_recall': '0.725', 'eval_runtime': '0.3678', 'eval_samples_per_second': '217.5', 'eval_steps_per_second': '13.59', 'epoch': '2'}
{'loss': '0.3251', 'grad_norm': '4.513', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.1853', 'eval_accuracy': '0.9375', 'eval_f1': '0.9351', 'eval_precision': '0.973', 'eval_recall': '0.9', 'eval_runtime': '0.3685', 'eval_samples_per_second': '217.1', 'eval_steps_per_second': '13.57', 'epoch': '3'}
{'eval_loss': '0.2107', 'eval_accuracy': '0.925', 'eval_f1': '0.9211', 'eval_precision': '0.9722', 'eval_recall': '0.875', 'eval_runtime': '0.3702', 'eval_samples_per_second': '216.1', 'eval_steps_per_second': '13.51', 'epoch': '4'}
{'train_runtime': '18.5', 'train_samples_per_second': '69.19', 'train_steps_per_second': '4.324', 'train_loss': '0.2319', 'epoch': '4'}
{'eval_loss': '0.2107', 'eval_accuracy': '0.925', 'eval_f1': '0.9211', 'eval_precision': '0.9722', 'eval_recall': '0.875', 'eval_runtime': '0.3525', 'eval_samples_per_second': '227', 'eval_steps_per_second': '14.19', 'epoch': '4'}
Fold 2 accuracy: 92.50%

--- Fold 3/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.2687', 'eval_accuracy': '0.9375', 'eval_f1': '0.9412', 'eval_precision': '0.8889', 'eval_recall': '1', 'eval_runtime': '0.367', 'eval_samples_per_second': '218', 'eval_steps_per_second': '13.62', 'epoch': '1'}
{'eval_loss': '0.1689', 'eval_accuracy': '0.95', 'eval_f1': '0.9512', 'eval_precision': '0.9286', 'eval_recall': '0.975', 'eval_runtime': '0.3633', 'eval_samples_per_second': '220.2', 'eval_steps_per_second': '13.76', 'epoch': '2'}
{'loss': '0.3151', 'grad_norm': '3.242', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.1477', 'eval_accuracy': '0.95', 'eval_f1': '0.9512', 'eval_precision': '0.9286', 'eval_recall': '0.975', 'eval_runtime': '0.3634', 'eval_samples_per_second': '220.2', 'eval_steps_per_second': '13.76', 'epoch': '3'}
{'eval_loss': '0.1402', 'eval_accuracy': '0.95', 'eval_f1': '0.9512', 'eval_precision': '0.9286', 'eval_recall': '0.975', 'eval_runtime': '0.3584', 'eval_samples_per_second': '223.2', 'eval_steps_per_second': '13.95', 'epoch': '4'}
{'train_runtime': '18.35', 'train_samples_per_second': '69.75', 'train_steps_per_second': '4.359', 'train_loss': '0.235', 'epoch': '4'}
{'eval_loss': '0.1402', 'eval_accuracy': '0.95', 'eval_f1': '0.9512', 'eval_precision': '0.9286', 'eval_recall': '0.975', 'eval_runtime': '0.3452', 'eval_samples_per_second': '231.7', 'eval_steps_per_second': '14.48', 'epoch': '4'}
Fold 3 accuracy: 95.00%

--- Fold 4/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3737', 'eval_accuracy': '0.8125', 'eval_f1': '0.8148', 'eval_precision': '0.8049', 'eval_recall': '0.825', 'eval_runtime': '0.3551', 'eval_samples_per_second': '225.3', 'eval_steps_per_second': '14.08', 'epoch': '1'}
{'eval_loss': '0.3567', 'eval_accuracy': '0.85', 'eval_f1': '0.8571', 'eval_precision': '0.8182', 'eval_recall': '0.9', 'eval_runtime': '0.3614', 'eval_samples_per_second': '221.4', 'eval_steps_per_second': '13.84', 'epoch': '2'}
{'loss': '0.2911', 'grad_norm': '0.7145', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.384', 'eval_accuracy': '0.85', 'eval_f1': '0.8462', 'eval_precision': '0.8684', 'eval_recall': '0.825', 'eval_runtime': '0.359', 'eval_samples_per_second': '222.8', 'eval_steps_per_second': '13.93', 'epoch': '3'}
{'eval_loss': '0.3625', 'eval_accuracy': '0.8625', 'eval_f1': '0.8642', 'eval_precision': '0.8537', 'eval_recall': '0.875', 'eval_runtime': '0.3602', 'eval_samples_per_second': '222.1', 'eval_steps_per_second': '13.88', 'epoch': '4'}
{'train_runtime': '18.13', 'train_samples_per_second': '70.59', 'train_steps_per_second': '4.412', 'train_loss': '0.2107', 'epoch': '4'}
{'eval_loss': '0.3625', 'eval_accuracy': '0.8625', 'eval_f1': '0.8642', 'eval_precision': '0.8537', 'eval_recall': '0.875', 'eval_runtime': '0.3444', 'eval_samples_per_second': '232.3', 'eval_steps_per_second': '14.52', 'epoch': '4'}
Fold 4 accuracy: 86.25%

--- Fold 5/5 ---

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: sagorsarker/bangla-bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'eval_loss': '0.3704', 'eval_accuracy': '0.85', 'eval_f1': '0.8378', 'eval_precision': '0.9118', 'eval_recall': '0.775', 'eval_runtime': '0.36', 'eval_samples_per_second': '222.2', 'eval_steps_per_second': '13.89', 'epoch': '1'}
{'eval_loss': '0.2915', 'eval_accuracy': '0.8625', 'eval_f1': '0.8608', 'eval_precision': '0.8718', 'eval_recall': '0.85', 'eval_runtime': '0.361', 'eval_samples_per_second': '221.6', 'eval_steps_per_second': '13.85', 'epoch': '2'}
{'loss': '0.3113', 'grad_norm': '7.597', 'learning_rate': '7.75e-06', 'epoch': '2.5'}
{'eval_loss': '0.2905', 'eval_accuracy': '0.8875', 'eval_f1': '0.8861', 'eval_precision': '0.8974', 'eval_recall': '0.875', 'eval_runtime': '0.3667', 'eval_samples_per_second': '218.2', 'eval_steps_per_second': '13.64', 'epoch': '3'}
{'eval_loss': '0.3219', 'eval_accuracy': '0.875', 'eval_f1': '0.8718', 'eval_precision': '0.8947', 'eval_recall': '0.85', 'eval_runtime': '0.3673', 'eval_samples_per_second': '217.8', 'eval_steps_per_second': '13.61', 'epoch': '4'}
{'train_runtime': '18.39', 'train_samples_per_second': '69.59', 'train_steps_per_second': '4.35', 'train_loss': '0.2255', 'epoch': '4'}
{'eval_loss': '0.3219', 'eval_accuracy': '0.875', 'eval_f1': '0.8718', 'eval_precision': '0.8947', 'eval_recall': '0.85', 'eval_runtime': '0.3554', 'eval_samples_per_second': '225.1', 'eval_steps_per_second': '14.07', 'epoch': '4'}
Fold 5 accuracy: 87.50%


======================================================================
FINAL COMPARISON: BanglaBERT (5-fold CV) vs. Original Thesis Results
======================================================================
  Column BanglaBERT Acc (mean ± std, %)  BanglaBERT F1 (mean, %)  Best ML (SGD)  Best DL (BiLSTM)                Fold accuracies  Best ML (KNN)  Best DL (LSTM)  Best ML (SGD/Multi-NB)  Best DL (BiLSTM/CNN/CNN-LSTM)
academic                   91.75 ± 1.70                    91.91           95.0              92.5 [88.8, 93.8, 92.5, 91.2, 92.5]            NaN             NaN                     NaN                            NaN
  mental                   90.75 ± 1.27                    90.90            NaN               NaN [92.5, 91.2, 91.2, 90.0, 88.8]          93.75           98.75                     NaN                            NaN
  social                   90.75 ± 3.32                    90.70            NaN               NaN [92.5, 92.5, 95.0, 86.2, 87.5]            NaN             NaN                    95.0                           92.5

Saved to banglabert_cv_vs_thesis_comparison.csv